name: Publish BFast NuGet

on:
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/publish-nuget.yaml
    with:
      project_path: src/cs/bfast/Vim.BFast/Vim.BFast.csproj
      test_project_path: src/cs/bfast/Vim.BFast.Tests/Vim.BFast.Tests.csproj
      package_name: Vim.BFast
    secrets:
      VIM_NUGET_PUSH: ${{ secrets.VIM_NUGET_PUSH }}
