name: Test merged C++

on:
  push:
    branches:
      - vadim/repo-setup
  # pull_request:
  #   branches:
  #     - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test_merged:
    runs-on: ubuntu-latest

    steps:

      ###########################################
      # CONFIG AND SETUP
      ###########################################
 
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetches the whole history in order to be able to merge with the base branch

      - name: Setup Git VIM Robot User Info
        run: |
          git config --global user.email "vim-robot@email.com"
          git config --global user.name "Vim Robot"

      - name: Merge with base
        run: git merge origin/develop
        # run: git merge origin/${GITHUB_BASE_REF} # GITHUB_BASE_REF is only defined for pull requests
        shell: bash

      ###########################################
      # BUILD
      ###########################################

      - name: Test
        shell: bash
        run: ./run-cpp-tests.sh
        working-directory: ./devops
